export const CLINICAL_DISCLAIMER =
  "⚠️ AI-Generated Analysis — This output is generated by an AI system and is intended " +
  "for clinical decision support only. It does not constitute medical advice. All findings " +
  "must be verified by a qualified healthcare professional before any clinical action is taken. " +
  "This tool may miss relevant findings or generate false positives.";

export const TASK_DISCLAIMER =
  "📋 Draft Tasks — These FHIR Task resources are drafts for clinician review. " +
  "They must be reviewed, modified if necessary, and approved by an authorized " +
  "provider before being finalized in the EHR system.";

export function wrapWithDisclaimer(content: string, type: "analysis" | "tasks" = "analysis"): string {
  const disclaimer = type === "tasks" ? TASK_DISCLAIMER : CLINICAL_DISCLAIMER;
  return `${content}\n\n---\n${disclaimer}`;
}
